
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rntdoretto/properties.git
          
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true