logging:
  level:
    org.springframework: ERROR
    com.renatodoretto.examples.microservices: DEBUG

server:
  port: 8085
  
spring:
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #heartbeats
    lease-expiration-duration-in-seconds: 20 #expiration time
    health-check-url-path: http://localhost:${server.port}/health
