spring:
  application:
    name: spring-boot-microservices-gateway
    
server:
  port: 8080
  servlet:
    context-path: /gateway
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
    
zuul:
  sensitive-headers: Cookie
