spring:
  application:
    name: currency-exchange
  profiles:
    active:
    - local
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8000
  
eureka:
  client:
#    register-with-eureka: true #auto-register
#    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka
  
#  cloud:
#    config:
#      uri:
#      - http://localhost:8888
#    discovery:
#      enabled: true
#      client:
#        simple:
#          local:
#            service-id: config-server