eureka:
  client:
    register-with-eureka: false #auto-register
    fetch-registry: false 
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
      
logging:
  level:
    org.springframework: ERROR
    com.renatodoretto.examples.microservices: DEBUG

server:
  port: 8761
  
spring:
  application:
    name: discovery
  profiles:
    active:
    - local