spring:
  application:
    name: currency-conversion
  profiles:
    active:
    - local
server:
  port: 8100

eureka:
  client:
#    register-with-eureka: true #auto-register
#    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#  cloud:
#    config:
#      uri:
#      - http://localhost:8888
#    discovery:
#      enabled: true
#      client:
#        simple:
#          local:
#            service-id: config-server

### Ribbon configuration without Discovery Server 
#currency-exchange:
#  ribbon:
#    listOfServers: http://localhost:8000,http://localhost:8001